# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_of_car', models.CharField(max_length=255)),
                ('plates_number', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=255)),
                ('color', models.TextField()),
                ('no_of_seats', models.IntegerField()),
                ('picture', models.ImageField(upload_to='photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField(max_length=255)),
                ('arrival_time', models.TimeField(max_length=255)),
                ('no_passengers', models.IntegerField()),
                ('ride_details', models.TextField()),
                ('sharing_ended', models.BooleanField(default=False)),
                ('cardetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.CarDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='photos/')),
                ('current_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_point', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_cost', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=255)),
                ('carsharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.CarSharing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
