# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:41
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20171205_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, null=True),
        ),
    ]
