# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20171210_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='picture',
            field=models.ImageField(upload_to='driverphotos/'),
        ),
    ]
