# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20171210_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
